TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'ByTorsten.Editors': TRUE
    userInterface:
      requireJsPathMapping:
        'ByTorsten.Editors': 'resource://ByTorsten.Editors/Public/Scripts/Inspector/Editors'